---
- name: block new install
  block:
#    - name: ensure tomcat directory exists
#      file:
#        path: "{{ install_source_dir }}/{{ unziped_capabilities_name }}"
#        state: directory

    - name: Copy and Unzip Install Files
      unarchive:
        src: "{{ capabilities_file }}"
        dest: "{{ capabilities_directory }}"

    - name: move files
      copy:
        src: "{{ capabilities_directory }}/{{ unziped_capabilities_name }}/"
        dest: "{{ capabilities_directory }}/"

    - name: Restart Service
      service:
        name: "{{ orchestrator_service }}"
        state: restarted
  when: install_capabilities == true
