---
- name: block new install
  block:
    - name: create extensions
      file:
        path: "{{ capabilities_directory }}"
        state: directory
        mode: '0755'

    - name: Copy and Unzip Install Files
      unarchive:
        src: "{{ capabilities_file }}"
        dest: "{{ capabilities_directory }}"

    - name: unzip Cap Files
      win_shell: |
        Get-ChildItem "{{ install_source_dir }}{{ unziped_capabilities_name }}" | Move-Item -Destination "{{ install_target_dir }}{{ orchestrator_dir }}\extensions"

    - name: Restart Service
      service:
        name: "{{ orchestrator_service }}"
        state: restarted
  when: install_capabilities == true
