---
- name: block new install
  block:
    - name: Copy and Unzip Install Files
      unarchive:
        src: "{{ capabilities_file }}"
        dest: "{{ install_source_dir }}/{{ unziped_capabilities_name }}"

    - name: move files
      copy:
        src: "{{ install_source_dir }}/{{ unziped_capabilities_name }}/"
        dest: "{{ capabilities_directory }}"

    - name: Restart Service
      service:
        name: "{{ orchestrator_service }}"
        state: restarted
  when: install_capabilities == true
