---
- name: Universal_Orchestrator.yaml
  hosts: all
  gather_facts: yes
  tasks:
  - name: include role
    include_role:
      name: linux_universal_orchestrator
    when: inventory_hostname in groups["linux"]

  - name: include role
    include_role:
      name: windows_universal_orchestrator
    when: inventory_hostname in groups["windows"]

  - name: include role
    include_role:
      name: anygateway
    when: inventory_hostname in groups["anygateway"]